# Generated by Django 4.2.14 on 2024-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('book_img', models.ImageField(upload_to='book_store_app/images')),
            ],
        ),
    ]
