# Generated by Django 5.0.7 on 2024-07-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
                ('publish_date', models.DateTimeField(null=True)),
                ('pages', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store_app.book')),
            ],
        ),
    ]
