# Generated by Django 5.0.7 on 2024-07-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0005_cart_book_id_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='book_id',
            new_name='book',
        ),
    ]
