# Generated by Django 5.0.7 on 2024-08-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0006_rename_book_id_cart_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookspecifications',
            old_name='book_id',
            new_name='book',
        ),
    ]
